name = "wappu-lingo"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

# Secrets Store bindings (used in production)
secrets_store_secrets = [
  { binding = "GRAVATAR_CLIENT_ID", store_id = "74de4b75b0b74545ad1210dc1db9c056", secret_name = "gravatar-client-id" }
]

[[d1_databases]]
binding = "DB"
database_name = "wappu-lingo-db"
database_id = "a8c64848-f8fc-4662-980f-5304dd2ff6bc"
