name = "wappu-lingo"
compatibility_date = "2024-01-01"
pages_build_output_dir = "dist"

[[vars]]
VITE_GRAVATAR_CLIENT_ID = "130494"

[[d1_databases]]
binding = "DB"
database_name = "wappu-lingo-db"
database_id = "a8c64848-f8fc-4662-980f-5304dd2ff6bc"
